### ISSUE TITLE
Mentor/Student can view percentage progress on goals

### ISSUE THREAD

**Issue by ksun86** [JIA-8100-Excelerate/Project-Management#16]
check page12 for details

**Comment by zmudge3** [comment]
## Story/Task Details
- [ ] Design visuals for goal progression
- [ ] Render visuals using frontend
- [ ] GET goals from Server

## Acceptance Scenarios
Scenario 1: A student chooses to view their percentage progress on all their goals
Given​ the student is on the home page;
When the student looks at the Home Dashboard;
Then Goals and their percent-completions are 

## Done Done Criteria
Customer has approved UI design and function, code is merged with master branch, and acceptance scenarios are satisfied.
